apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app-service
    app: app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  # Ancla con el pod (identificador del pod, los labels)
  selector:
    app: app
    type: mvc
