apiVersion: v1
kind: Pod
metadata:
  name: mssql-pod
  # identificadores del pod
  labels:
      app: app
      name: mssql-pod
spec:
  containers:
    - name: mssql
      image: mcr.microsoft.com/mssql/rhel/server:2019-latest
      ports:
        - containerPort: 1433
      env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA # el usuario es "sa"
          value: "Y"
        - name: SA_PASSWORD
          value: "vaxidrez.2025"
        # - name: MSSQL_SA_PASSWORD
        #  valueFrom:
        #    secretKeyRef:
        #      name: vaxidrez.2025
        #      key: SA_PASSWORD 
          
        